# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 931560669438b63f627fb0a1a837d09c3bb2924df0bb181d0fa00f528f05c054e4c78513af36f57c669ef9c99cbe91775fec5b594304999ee8d99f627fb66a6f

test:
  secret_key_base: 244c9b8b0307d642b5c87c76c8d726fcc1345710a66ecc7bb28fa86eeb1f82d2f05920e203a9632810022b7c60640b294a45755e049968d7fafcf8131041c49c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
